### ISSUE TITLE
Problem in Login-SignUp Screen

### ISSUE THREAD

**Issue by Varun-Sethi-Dev** [sourabhkumar47/ResQFood#39]
**Describe the bug**
While trying to get otp for mobile sign-up it faces problem.

**Expected behavior**
An request to send opt must be sent to firebase..

**Screenshots**
<img width="872" alt="error in sign-in" src="https://github.com/sourabhkumar47/ResQFood/assets/157269803/a115f081-b673-4a63-92f2-0850191ab569">

**Additional context**

- Ensure that the package name of your app in the Firebase Console matches the package name in your Android project.
- Check if the SHA-1 and SHA-256 fingerprints in the Firebase Console match the ones generated for your app.
- If you've recently made changes to your app's package name or signing key, ensure that you've updated the corresponding information in the Firebase Console.

**Comment by Varun-Sethi-Dev** [comment]
I think that the project admin must link the firebase with his account would be a better option.Just a thought does not know what will do.

**Comment by HemangMishra1234** [comment]
The problem is that the SHA1 fingerprint is required for google sign in. Since only my sha1 is added to the console, the feature is working in my app. But because other people will have different sha1 fingerprints, it is not working for them. One solution is that I should manually add all fingerprints, which is not feasible. Let me know if you have any solutions. Is the phone number sign in working? Because that also requires SHA256 fingerprints for authentication.

**Comment by shivanshu11092003** [comment]
Getting Errors in Login

**Comment by sourabhkumar47** [comment]
> Getting Errors in Login

Login with email and password
